org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configureondemand=true

mod.id=forever-pets
mod.name=Forever Pets
mod.version=1.1.0
mod.group=cat.anya.foreverpets
mod.description=Makes tamed cats, wolves and parrots immortal.
